#include "main.h"
#include "ftmtxt.h"
#include "itfile.h"

#include <iostream>

int main(int argc, char* argv[])
{
	if (argc < 2) {
		std::cout << "ftmtxt2seq v0.1 by cybermind" << std::endl;
		std::cout << std::endl;
		std::cout << "Converts text files generated by text export feature" << std::endl;
		std::cout << "of FamiTracker into IT tracker module files." << std::endl;
		std::cout << std::endl;
		std::cout << "Usage: ftmtxt2seq ftmtxtfile" << std::endl;
		std::cout << "ftmtxtfile - file name of text exported FTM" << std::endl;
		exit(1);
		return 1;
	}
	FTMtxt ftmtxt;
	ftmtxt.loadText(argv[1]);
	ITFile itfile;
	itfile.convertFTMtxt(ftmtxt);
	std::string outFile;
	outFile = argv[1] + std::string(".it");
	itfile.writeOutput(outFile.c_str());
	return 0;
}
